title: Rhiannon Payne
description: > # this means to ignore newlines until "baseurl:"
  Rhiannon Payne is an SF-based entrepreneur, startup consultant, writer, & speaker. Currently writing a book titled "The Remote Work Era."
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://maverickmac.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: "https://twitter.com/rhiannon_io" #if your site has a twitter account, enter it here

# Author Settings
author: Rhiannon Payne # add your name
author-img: Rhiannon Payne - Author Photo.png # add your photo
about-author: I'm a San Francisco-based entrepreneur, startup consultant, writer, speaker, & adventurer. In 2017 I founded <a href="https://seafoam.media" target="_blank">Sea Foam Media & Technology</a> to help startups tell their stories & build exciting products. I am also passionate about <a href="https://remoteworkera.com" target="_blank">The Remote Work Era</a>, with a book to be published in 2020. # add description
social-twitter: rhiannon_io # add your Twitter handle
social-facebook: rhiannonmarypayne # add your Facebook handle
social-github: rhiannon-io # ig handle
social-linkedin: rhipayne # add your Linkedin handle
social-email: payne@rhiannon.io # add your Email address

# Disqus
discus-identifier: Rhiannon Payne # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
