# Site settings
title:          Maverick Mac
description:    "A curated list of awesome mac applications and utilities"
baseurl:        ""
url:            "https://maverickmac.github.io"

# Google Analytics
#google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Maverick Mac
  url:          https://maverickmac.github.io
  email:        maverick.mac@linuxmail.in

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         maverick_mac17
